version: '3.7'

services:
  nodets:
    container_name: typescript-dev-app
    build:
      context: .
    environment:
      - PORT=8080
      - DB_HOST=postgresdb
      - DB_PORT=5430
      - DB_USERNAME=devuser
      - DB_PASSWORD=11657
      - DB_NAME=devdb
      - JWT_SECRET=yourjwtsecret
    ports:
      - 8080:8080
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    image: kartoza/postgis:12.0
    ports:
      - 5430:5432
    volumes:
      - /Users/$USER/pgdata:/var/lib/postgresql/12/main
      - ./docker-setup/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=devuser
      - PGUSER=devuser
      - POSTGRES_PASS=11657
      - PGPASSWORD=11657
      - POSTGRES_DBNAME=devdb
      - PGDATABASE=devdb
      - PGHOST=localhost
      - ALLOW_IP_RANGE=0.0.0.0/0
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]

networks:
  default:
    name: typescript-dev-network
