services:
  api:
    container_name: typescript-api
    build: .
    environment:
      - PORT=8080
      - DB_USERNAME=devuser
      - DB_HOST=postgresdb
      - DB_NAME=devdb
      - DB_PASSWORD=pass11657
      - DB_PORT=5438
      - JWT_SECRET=yourjwtsecret
    ports:
      - 8080:8080
    depends_on:
     - postgresdb

  postgresdb:
    container_name: postgresdb
    restart: unless-stopped
    image: postgres:16-alpine
    ports:
      - '5438:5432'
    volumes:
      - /Users/$USER/pgdata:/var/lib/postgres
      - ./docker-setup/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=mainuser
      - POSTGRES_PASSWORD=pass11657
      - POSTGRES_DB=mydb
